### PR TITLE
Fixes #174: remove entire GC mechanism and use try-with-resources instead

### LINKED ISSUE #174: GC hooks for closing resources are not working
It would appear the GC hooks are not working properly to close resources on the file system.

This likely needs to be reconsidered and redesigned. RamFileSystem is not too much of an issue for now but the TempFileSystem integrations will be a problem if resources do not get cleaned up.

### PR DESCRIPTION
**Pull request by ascopes**
This set of changes rips out a bunch of internal components around dealing with file managements that were not cleaning up correctly.

Previously, I used GC hooks to detect this stuff. It worked to begin with but it is very flaky with regards to circular references preventing object cleanup.

The new solution will provide an explicit `Workspace` type that holds all of the file resources. This is initialised by the user in their test and provided to the compiler when calling `JctCompiler#compile`. This workspace type implements the `Closeable` interface, so it can be used with a `try-with-resources` instead, removing the need for any GC hooks anywhere.

An example of how a test would look under this system:

```java
class SomeTest {
  @JavacCompilerTest
  void testTheResourceCompilesCorrectly(JctCompiler<?, ?> compiler) {
    try (var workspace = Workspace.newWorkspace()) {
      workspace
          .createSourcePathPackage()
          .createFile("com/example/HelloWorld.java").withContents("""
              package com.example;

              public class HelloWorld {
                public static void main(String[] args) {
                  System.out.println("Hello, World");
                }
              }
              """
          );

      var compilation = compiler
          .compile(workspace);

      assertThatCompilation(compilation)
          .isSuccessfulWithoutWarnings();

      assertThatCompilation(compilation)
          .classOutput().packages()
          .fileExists("com/example/HelloWorld.class")
          .isNotEmptyFile();
    }
  }
}
```

The directory system that should be used can be provided as an argument to the `Workspace` constructor:

```java
var workspace = Workspace.newWorkspace(PathStrategy.RAM_DIRECTORIES);
// or
var workspace = Workspace.newWorkspace(PathStrategy.TEMP_DIRECTORIES);
```

The default if no arguments are provided is to use `PathStrategy.RAM_DIRECTORIES`.

Other changes that facilitate this change include:

- TempDirectoryFactory is removed.
- JctFileManagerBuilder is removed, functionality is now in JctCompilationFactory.
- JctCompilationFactory is now internal and hidden by the module descriptor.
- JctCompilationImpl is now internal and hidden by the module descriptor.
- AbstractJctCompiler is now internal and hidden by the module descriptor.
- JctFileManagerImpl is now internal and hidden by the module descriptor.
- TempDirectory is now internal and hidden by the module descriptor.
- RamDirectory is now internal and hidden by the module descriptor.
- TempDirectory no longer supports closure hooks or the closeOnGc argument.
- RamDirectory no longer supports closure hooks or the closeOnGc argument.
- BasicPathWrapperImpl is now internal and hidden by the module descriptor.
- GarbageDisposalUtils has been removed entirely.
- The `pathwrappers` package no longer exists. Types are now in the `workspaces` package.
- Reintroduced `impl` subpackages for internal details.
- Closeable types, including `Container` and `ContainerGroup`-derived types, will now throw IOException in their signature. The `workspace` class is exempt from this, instead throwing UncheckedIOException to prevent polluting test cases with checked exception requirements.
- `byte[] getClassBinary(String binaryName) throws IOException;` methods are now removed as they were not used anyway. They were a leftover artifact of the old class loader mechanism that was used before I switched to using URLClassLoader.

### CODE REVIEW

File: acceptance-tests/acceptance-tests-checkerframework/src/test/groovy/io/github/ascopes/jct/acceptancetests/checkerframework/CheckerNullTest.groovy [hunk 1]
```diff
@@ -25,7 +25,7 @@ import org.junit.jupiter.api.parallel.Execution
 import org.junit.jupiter.api.parallel.ExecutionMode
 
 import static io.github.ascopes.jct.assertions.JctAssertions.assertThatCompilation
-import static io.github.ascopes.jct.pathwrappers.RamDirectory.newRamDirectory
+import static io.github.ascopes.jct.workspaces.impl.RamDirectory.newRamDirectory
```
Comment (ascopes) [inline acceptance-tests/acceptance-tests-checkerframework/src/test/groovy/io/github/ascopes/jct/acceptancetests/checkerframework/CheckerNullTest.groovy:28]: - [ ] Exclude impl types from JavaDocs.
- [ ] Update example snippet in `README.md` and `module-info.java`.

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctCompiler.java [hunk 2]
```diff
@@ -146,383 +144,6 @@
...
-   *   <li>A path to a ZIP containing a <strong>package</strong> or <strong>module</strong>.</li>
-   * </ul>
-   *
-   * <p><strong>Note:</strong> to add modules, consider using
-   * {@link #addModulePath(String, PathWrapper)} instead.</p>
-   *
-   * @param pathLike the path-like object to add.
-   * @return this compiler object for further call chaining.
-   */
-  default C addClassPath(PathWrapper pathLike) {
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctCompiler.java:266]: - [ ] Re-add these methods to the `Workspace` class.

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctCompilationFactory.java [hunk 3]
```diff
@@ -59,39 +66,48 @@
...
-      JctFlagBuilder flagBuilder
-  ) {
+  public JctCompilationImpl build() {
     try {
       var flags = buildFlags(compiler, flagBuilder);
       var diagnosticListener = buildDiagnosticListener(compiler);
       var writer = buildWriter(compiler);
 
-      try (var fileManager = buildFileManager(compiler, builder)) {
+      try (var fileManager = buildFileManager()) {
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctCompilationFactory.java:110]: - [ ] Remove closable semantics for JctFileManager as it gets closed by the compiler and this does not make sense when we perform one or more compiler passes. Nothing is closed now either.

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctCompilationFactory.java [hunk 4]
```diff
@@ -219,35 +208,32 @@ private List<String> buildFlags(A compiler, JctFlagBuilder flagBuilder) {
...
-   * @param builder  the file manager builder to build from.
-   * @return the file manager to use.
-   */
-  private JctFileManager buildFileManager(A compiler, JctFileManagerBuilder builder) {
-    return uncheckedIo(() -> builder.createFileManager(determineRelease(compiler)));
+  private JctFileManager buildFileManager() {
+    var fileManager = new JctFileManagerImpl(determineRelease());
+
+    // Copy all other explicit locations across first to give them priority.
+    workspace.getPaths().forEach((location, paths) ->
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctCompilationFactory.java:215]: - [ ] Use a procedural set of loops here.

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctCompilationFactory.java [hunk 5]
```diff
@@ -442,14 +383,112 @@ private String determineRelease(JctCompiler<?, ?> compiler) {
...
+    if (!fileManager.hasLocation(location)) {
+      var dir = workspace.createPath(location);
+      fileManager.addPath(location, dir);
+    }
+  }
+
+  private void configureClassPath(JctFileManagerImpl fileManager) {
+    if (compiler.isInheritClassPath()) {
+      for (var path : jvmClassPath.access()) {
+        var wrapper = wrap(path);
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctCompilationFactory.java:396]: - [ ] Add logging for these events.

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/package-info.java [hunk 6]
```diff
@@ -13,22 +13,15 @@
...
- * Tests for {@link GarbageDisposalUtils}.
- *
- * @author Ashley Scopes
+ * TODO(ascopes): description.
  */
-@DisplayName("GarbageDisposalUtils tests")
-class GarbageDisposalUtilsTest implements StaticClassTestTemplate {
+@API(since = "0.0.1", status = Status.INTERNAL)
+@NonNullApi
+@NonNullImpl
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/package-info.java:21]: - [ ] Ensure API, NonNullApi and NonNullImpl usage is consistent across all packages.

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/javac/package-info.java [hunk 7]
```diff
@@ -14,9 +14,9 @@
  * limitations under the License.
  */
 /**
- * Javac integrations.
+ * TODO(ascopes): description.
  */
-@API(since = "0.0.1", status = Status.EXPERIMENTAL)
+@API(since = "0.0.1", status = Status.INTERNAL)
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/javac/package-info.java:19]: - [ ] Update all classes in this package to be flagged as INTERNAL

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/assertions/AbstractJavaFileObjectAssert.java [hunk 8]
```diff
@@ -36,9 +36,9 @@
 /**
  * Abstract assertions for {@link JavaFileObject Java file objects}.
  *
- * @author Ashley Scopes
  * @param <I> the implementation class that is extending this class.
  * @param <A> the file object implementation type.
+ * @author Ashley Scopes
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/assertions/AbstractJavaFileObjectAssert.java:41]: - [ ] Re-run code formatter across all packages to ensure consistency.

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/AbstractJctCompiler.java [hunk 9]
```diff
@@ -76,44 +75,66 @@
...
+
+  @Override
+  public JctCompilationImpl compile(Workspace workspace) {
+    return new JctCompilationFactory<>(workspace, myself(), jsr199Compiler, flagBuilder).build();
+  }
+
+  @Override
+  public final <E extends Exception> A configure(JctCompilerConfigurer<E> configurer) throws E {
+    requireNonNull(configurer, "configurer");
+    var me = myself();
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/AbstractJctCompiler.java:134]: - [ ] Is the call to `myself` needed, or will `this` work here?

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctCompilationFactory.java [hunk 10]
```diff
@@ -219,35 +208,32 @@ private List<String> buildFlags(A compiler, JctFlagBuilder flagBuilder) {
...
+    configureAnnotationProcessorPaths(fileManager);
+
+    // We have to manually create this one as javac will not attempt to access it lazily. Instead,
+    // it will just abort if it is not present. This means we cannot take advantage of the
+    // PathLocationRepository creating the roots as we try to access them for this specific case.
+    createLocationIfNotPresent(fileManager, StandardLocation.CLASS_OUTPUT);
+
+    // Annotation processors that create files will need this directory to exist if it is to
+    // work properly.
+    createLocationIfNotPresent(fileManager, StandardLocation.SOURCE_OUTPUT);
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctCompilationFactory.java:232]: - [ ] These locations could be kept in a list and iterated across.

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctCompilationFactory.java [hunk 11]
```diff
@@ -442,14 +383,112 @@ private String determineRelease(JctCompiler<?, ?> compiler) {
...
+        break;
+
+      case INCLUDE_DEPENDENCIES: {
+        // https://stackoverflow.com/q/53084037
+        // Seems that javac will always use the classpath to implement this behaviour, and never
+        // the module path. Let's keep this simple and mimic this behaviour. If someone complains
+        // about it being problematic in the future, then I am open to change how this works to
+        // keep it sensible.
+        fileManager.copyContainers(
+            StandardLocation.CLASS_PATH,
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctCompilationFactory.java:454]: - [ ] Do I need to do this for the annotation processor module path as well?
- [ ] ...if so, can this be represented as a Map and a loop rather than hardcoding it?

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctCompilationFactory.java [hunk 12]
```diff
@@ -442,14 +383,112 @@ private String determineRelease(JctCompiler<?, ?> compiler) {
...
+      case DISABLED:
+      default:
+        // There is nothing to do to the file manager to configure annotation processing at this
+        // time.
+        break;
+    }
+  }
+
+  private PathWrapper wrap(Path path) {
+    return new BasicPathWrapperImpl(path);
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/impl/JctCompilationFactory.java:470]: - [ ] Could this be inlined?

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/AbstractPackageContainerGroup.java [hunk 13]
```diff
@@ -128,7 +130,7 @@ public void close() throws IOException {
     for (var container : containers) {
       try {
         container.close();
-      } catch (IOException ex) {
+      } catch (Exception ex) {
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/AbstractPackageContainerGroup.java:133]: - [ ] Should this only catch IOException now that the superinterface uses Closeable rather than AutoCloseable?

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/ModuleContainerGroupImpl.java [hunk 14]
```diff
@@ -93,19 +96,19 @@ public void addModule(String module, PathWrapper path) {
 
   @Override
   public void close() throws IOException {
-    var exceptions = new ArrayList<IOException>();
+    var exceptions = new ArrayList<Throwable>();
     for (var group : modules.values()) {
       try {
         group.close();
-      } catch (IOException ex) {
+      } catch (Exception ex) {
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/ModuleContainerGroupImpl.java:103]: - [ ] Should this use IOException again?

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/ModuleContainerGroupImpl.java [hunk 15]
```diff
@@ -93,19 +96,19 @@ public void addModule(String module, PathWrapper path) {
...
         exceptions.add(ex);
       }
     }
 
     if (!exceptions.isEmpty()) {
-      var ex = new IOException("One or more module impl failed to close");
-      exceptions.forEach(ex::addSuppressed);
-      throw ex;
+      var newEx = new IOException("One or more module impl failed to close");
+      exceptions.forEach(newEx::addSuppressed);
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/ModuleContainerGroupImpl.java:110]: - [ ] Maybe this could go in IoExceptionUtils. If we use this logic elsewhere for non-IO exceptions, I could probably repurpose IoExceptionUtils as just ExceptionUtils

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/TestDirectory.java [hunk 16]
```diff
@@ -51,65 +49,54 @@
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 
+// TODO(ascopes): interface time.
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/TestDirectory.java:52]: - [ ] Expose this functionality via an interface and make this class internal.

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/Workspace.java [hunk 17]
```diff
@@ -0,0 +1,108 @@
...
+import java.util.HashMap;
+import java.util.List;
+import java.util.Map;
+import java.util.function.Function;
+import javax.tools.JavaFileManager.Location;
+import org.apiguardian.api.API;
+import org.apiguardian.api.API.Status;
+
+// TODO(ascopes): interface time.
+public class Workspace implements AutoCloseable {
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/Workspace.java:21]: - [ ] Do I want to use an interface for this? The impl can be exposed via a static method on the interface.

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/Workspace.java [hunk 18]
```diff
@@ -0,0 +1,108 @@
...
+
+  public void addPath(Location location, String moduleName, Path path) {
+    addPath(new ModuleLocation(location, moduleName), path);
+  }
+
+  public TestDirectory createPath(Location location, String moduleName) {
+    return createPath(new ModuleLocation(location, moduleName));
+  }
+
+  public Map<Location, List<PathWrapper>> getPaths() {
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/Workspace.java:80]: - [ ] Should the type params here be covariant

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/Workspace.java [hunk 19]
```diff
@@ -0,0 +1,108 @@
...
+    // Create an immutable copy.
+    var pathsCopy = new HashMap<Location, List<PathWrapper>>();
+    paths.forEach((location, list) -> pathsCopy.put(location, List.copyOf(list)));
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/Workspace.java:83]: - [ ] Move to IterableUtils

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/Workspace.java [hunk 20]
```diff
@@ -0,0 +1,108 @@
...
+  }
+
+  /**
+   * Strategy to use for configuring new test directories.
+   *
+   * @author Ashley Scopes
+   * @since 0.0.1
+   */
+  @API(since = "0.0.1", status = Status.INTERNAL)
+  public enum PathStrategy {
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/Workspace.java:94]: - [ ] Move to separate file

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/impl/TempDirectory.java [hunk 21]
```diff
@@ -44,64 +45,40 @@
...
+  }
+
+  @Override
+  public void close() throws IOException {
+    LOGGER.debug(
+        "Deleting temporary directory ({} @ {})",
+        rootDirectory.toUri(),
+        rootDirectory.getFileSystem()
+    );
+    RecursiveDeleter.deleteAll(rootDirectory);
```
Comment (ascopes) [inline java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/impl/TempDirectory.java:67]: - [ ] If we do not use the deleter elsewhere, we may be able to inline this call and remove that class.

File: java-compiler-testing/src/test/java/io/github/ascopes/jct/testing/integration/BasicModuleCompilationIntegrationTest.java [hunk 22]
```diff
@@ -1,111 +1,111 @@
...
-    assertThatCompilation(compilation)
-        .classOutput()
-        .packages()
-        .fileExists("module-info.class")
-        .isNotEmptyFile();
-  }
-}
+///*
+// * Copyright (C) 2022 - 2022 Ashley Scopes
+// *
```
Comment (ascopes) [inline java-compiler-testing/src/test/java/io/github/ascopes/jct/testing/integration/BasicModuleCompilationIntegrationTest.java:3]: - [ ] Fix this test

File: java-compiler-testing/src/test/java/io/github/ascopes/jct/testing/integration/BasicMultiModuleCompilationIntegrationTest.java [hunk 23]
```diff
@@ -1,234 +1,234 @@
...
+// * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// * See the License for the specific language governing permissions and
+// * limitations under the License.
+// */
+//package io.github.ascopes.jct.testing.integration;
+//
+//import static io.github.ascopes.jct.assertions.JctAssertions.assertThatCompilation;
+//import static io.github.ascopes.jct.pathwrappers.RamDirectory.newRamDirectory;
+//import static io.github.ascopes.jct.pathwrappers.TempDirectory.newTempDirectory;
+//
```
Comment (ascopes) [inline java-compiler-testing/src/test/java/io/github/ascopes/jct/testing/integration/BasicMultiModuleCompilationIntegrationTest.java:21]: - [ ] Fix this test

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/ModuleContainerGroupImpl.java (hunk 15 above)
Comment (ascopes) [reply java-compiler-testing/src/main/java/io/github/ascopes/jct/containers/impl/ModuleContainerGroupImpl.java:110]: Not going to do this for now, can see little benefit.

File: java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/Workspace.java (hunk 19 above)
Comment (ascopes) [reply java-compiler-testing/src/main/java/io/github/ascopes/jct/workspaces/Workspace.java:83]: No longer relevant
